export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const FETCH_ORDER_START = 'FETCH_ORDER_START';
export const FETCH_ORDER_SUCCES = 'FETCH_ORDER_SUCCES';
export const FETCH_ORDER_FAILED = 'FETCH_ORDER_FAILED';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const MAIN_ORDERS_START = 'MAIN_ORDERS_START';
export const MAIN_ORDERS_SUCCESS = 'MAIN_ORDERS_SUCCESS';
export const MAIN_ORDERS_FAIL = 'MAIN_ORDERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOG_OUT = 'AUTH_LOG_OUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';